[project]
name = "voz"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "faster-whisper>=1.2.1",
    "numpy>=2.4.2",
    "pillow>=12.1.0",
    "pyaudio>=0.2.14",
    "pyautogui>=0.9.54",
    "pynput>=1.8.1",
    "pyperclip>=1.11.0",
    "torch==2.5.1",
]

[[tool.uv.index]]
url = "https://download.pytorch.org/whl/cu121"
